#PP 2.0

CLTB               GGU-------CCGCGCCAAGCCCGUCCCCGCC
MTCH1              GUCCCACCCGCCGCACCACGCUCCCGAGCUCC
MZT2B              GGCCCCGUCCCCGCGCUCCCGCCCCUCCCGCC
LMO2               GGUCCCCUCCCCGCCCCUAGGCCGCCGCCCCC

#END

#SECTION BASEPAIRS

#BPCUT 0.001

1 14 0.00103

#END
